### ISSUE TITLE
Test Failed - Error in loading assets JSMIN Issue?

### ISSUE THREAD

**Issue by drdavient** [xcreatelabs/playir#33]
I'm getting a js error popup frequently now when loading any scene. From the error it looks to be jsmin related? Something up in their network code?

TEST FAILED    at GetStackTrace (http://playir.com/jsmin/engine.js:1:1228)    at Function.CC.ASSERT (http://playir.com/jsmin/engine.js:1:2041)    at Function.ObjMesh.LoadOBJ (http://playir.com/jsmin/external.js:2:735)    at CCPrimitiveOBJ.loadData (http://playir.com/jsmin/engine.js:6:22651)    at CCURLRequest.callback (http://playir.com/jsmin/engine.js:6:20792)    at http://playir.com/jsmin/engine.js:8:8960    at http://playir.com/jsmin/engine.js:8:3793    at IDBRequest.request.onsuccess (http://playir.com/jsmin/engine.js:8:4414)

**Comment by drdavient** [comment]
To Recreate Play "Dave's Fighting Game". (ID 338)

Select Character, and click, "Join Online Battle"

**Comment by drdavient** [comment]
My bad. I was using a map i didn't have access to (map.295) This meant that I couldn't load some objects. Perhaps a permissions issue? Replacing that with my correct map (map.297) fixed this again.
